from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session
from io import BytesIO
from ..database import get_db
from ..models import Scan
from ..dependencies.auth import get_current_user
from ..models.user import User

router = APIRouter()

def _make_pdf(scan: Scan) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []
    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=18,
                                  textColor=colors.HexColor("#1a237e"))
    story.append(Paragraph("NirikshanX Compliance Report", title_style))
    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011", styles["Normal"]))
    story.append(Spacer(1, 0.4*cm))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a237e")))
    story.append(Spacer(1, 0.3*cm))

    overall = scan.overall_status.value if scan.overall_status and hasattr(scan.overall_status, "value") else str(scan.overall_status)
    meta = [
        ["Case ID:", str(scan.id)], ["Product:", scan.product_name], ["Category:", scan.category],
        ["Date:", scan.created_at.strftime("%d %B %Y, %H:%M")],
        ["Status:", overall],
        ["Compliance Score:", f"{scan.compliance_score}%" if scan.compliance_score is not None else "N/A"],
    ]
    t = Table(meta, colWidths=[5*cm, 10*cm])
    t.setStyle(TableStyle([
        ("FONT", (0,0), (-1,-1), "Helvetica"), ("FONTSIZE", (0,0), (-1,-1), 10),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("BACKGROUND", (0,0), (-1,-1), colors.HexColor("#f5f5f5")),
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey), ("PADDING", (0,0), (-1,-1), 5),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    story.append(Paragraph("Extracted Declarations", styles["Heading2"]))
    rows = [["Field", "Extracted Value", "Confidence", "Present"]]
    for d in scan.declarations:
        rows.append([d.field_name, d.extracted_value or "NOT FOUND", f"{d.confidence:.0%}", "Yes" if d.is_present else "No"])
    if len(rows) > 1:
        dt = Table(rows, colWidths=[5*cm, 7*cm, 3*cm, 2*cm])
        dt.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1a237e")),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 9),
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("PADDING", (0,0), (-1,-1), 4),
        ]))
        story.append(dt)
    story.append(Spacer(1, 0.5*cm))

    story.append(Paragraph("Violations & Compliance Checks", styles["Heading2"]))
    for v in scan.violations:
        sev = v.severity.value if hasattr(v.severity, "value") else str(v.severity)
        story.append(Paragraph(f"[{sev}] {v.message}", styles["Normal"]))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Paragraph(
        "This report is generated by NirikshanX. AI findings are indicative and require human review before legal enforcement.",
        styles["Italic"]
    ))
    doc.build(story)
    return buf.getvalue()

@router.get("/{scan_id}/pdf")
def download_pdf(scan_id: int, db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    scan = db.query(Scan).filter(Scan.id == scan_id).first()
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")
    pdf_bytes = _make_pdf(scan)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=NirikshanX-Report-{scan_id}.pdf"}
    )